# Generated by Django 4.2.25 on 2025-11-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('UserType', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handifyapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('Rating', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handifyapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaints', models.CharField(blank=True, max_length=200, null=True)),
                ('Reply', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handifyapp.usertable')),
            ],
        ),
    ]
