# Generated by Django 4.2.25 on 2025-11-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
