# Generated by Django 4.2.25 on 2025-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handifyapp', '0002_alter_complaintstable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='date',
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
